---
- hosts: localhost

  tasks:
    - block:
        - name: Obtain SSO token with using username/password credentials
          ovirt_auth:
            url: "{{ ovirt_url }}"
            username: {{ ovirt_username }}
            password: {{ ovirt_password }}

        - ovirt_vms_facts:
            pattern: name=*
        - debug:
            var: ovirt_vms

      always:
        - name: Always revoke the SSO token
          ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"
