---
- hosts: localhost

  tasks:
    - block:

    # https://docs.ansible.com/ansible/latest/ovirt_auth_module.html

        - name: Obtain SSO token
          ovirt_auth:
            url: "{{ ovirt_url }}"
            username: "{{ ovirt_username }}"
            password: "{{ ovirt_password }}"
            insecure: true

        # - name: ovirt_vms_facts
        #   ovirt_vms_facts:
        #     auth: "{{ ovirt_auth }}"
        #     pattern: name=Test-RHEL-1
        # - debug:
        #     var: ovirt_vms

        # - name: ovirt_clusters_facts
        #   ovirt_clusters_facts:
        #     auth: "{{ ovirt_auth }}"
        #     pattern: name=*
        # - debug:
        #     var: ovirt_clusters

        # https://docs.ansible.com/ansible/latest/ovirt_disk_module.html

        # Create and attach new disk to VM
        - name: Create shared disk
          ovirt_disk:
            auth: "{{ ovirt_auth }}"
            name: shared_disk001
            format: cow
            # interface: virtio
            shareable: true
            size: 10GiB
            state: detached
            storage_domain: "{{ storage_domain }}"
            wait: true

        # https://docs.ansible.com/ansible/latest/ovirt_vms_module.html

        # - name: Create first VM
        #   ovirt_vms:
        #     auth: "{{ ovirt_auth }}"
        #     state: present
        #     name: test001
        #     template: "{{ vm_template }}"
        #     cluster: "{{ cluster }}"
        #     storage_domain: "{{ storage_domain }}"

        # - name: Create second VM
        #   ovirt_vms:
        #     auth: "{{ ovirt_auth }}"
        #     state: present
        #     name: test002
        #     template: "{{ vm_template }}"
        #     cluster: "{{ cluster }}"
        #     storage_domain: "{{ storage_domain }}"

      always:
        - name: Revoke SSO token
          ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"
