---
- hosts: localhost

  tasks:
    - block:

    # https://docs.ansible.com/ansible/latest/ovirt_auth_module.html

        - name: Obtain SSO token
          ovirt_auth:
            url: "{{ ovirt_url }}"
            username: "{{ ovirt_username }}"
            password: "{{ ovirt_password }}"
            insecure: true

        # - ovirt_vms_facts:
        #     auth: "{{ ovirt_auth }}"
        #     pattern: name=*
        # - debug:
        #     var: ovirt_vms

        - ovirt_cluster_facts:
            auth: "{{ ovirt_auth }}"
            pattern:
              name: '*'
        - debug:
            var: ovirt_clusters

        # https://docs.ansible.com/ansible/latest/ovirt_vms_module.html

        - name: Create VM
          ovirt_vms:
            auth: "{{ ovirt_auth }}"
            state: present
            name: "{{ vm_name }}"
            template: "{{ vm_template }}"

        - name: Register VM
          ovirt_vms:
            auth: "{{ ovirt_auth }}"
            state: registered
            storage_domain: "{{ storage_domain }}"
            cluster: "{{ cluster }}"
            name: "{{ vm_name }}"

      always:
        - name: Revoke SSO token
          ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"
