---
- hosts: localhost

  tasks:
    - block:

    # https://docs.ansible.com/ansible/latest/ovirt_auth_module.html

      - name: Obtain SSO token
        ovirt_auth:
          url: "{{ ovirt_url }}"
          username: "{{ ovirt_username }}"
          password: "{{ ovirt_password }}"
          insecure: true

      - name: Create shared disk
        ovirt_disks:
          auth: "{{ ovirt_auth }}"
          name: shared_disk
          format: raw
          # interface: virtio
          shareable: true
          size: 10GiB
          state: detached
          storage_domain: "{{ storage_domain }}"
          wait: true
      - debug:
          var: shared_disk

      # https://docs.ansible.com/ansible/latest/ovirt_vms_module.html

      # - name: Create first VM
      #   ovirt_vms:
      #     auth: "{{ ovirt_auth }}"
      #     state: present
      #     name: test001
      #     template: "{{ vm_template }}"
      #     cluster: "{{ cluster }}"
      #     storage_domain: "{{ storage_domain }}"

      # - name: Create second VM
      #   ovirt_vms:
      #     auth: "{{ ovirt_auth }}"
      #     state: present
      #     name: test002
      #     template: "{{ vm_template }}"
      #     cluster: "{{ cluster }}"
      #     storage_domain: "{{ storage_domain }}"

      always:
        - name: Revoke SSO token
          ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"
